title: Valentin Six # your name (or website title) here
logo: "jacobins.jpg" # your photo (or logo) here
description: # your text below (remove <br> elements if you don't need line breaks)
  Hi there ! Im an undergraduate student at Télécom SudParis (IP Paris) and I am happy to share some of my projects on this page.
  My interest for Machine Learning and Deep Learning has been growing over the years and I am thrilled to share my first ML and DL projects !
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/valentin-six/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
