title: Valentin Six # your name (or website title) here
#logo: "images/jacobins.jpg" # your photo (or logo) here
description:
  Hi there ! I'm a graduate Computer Science student at Télécom SudParis (Institut Polytechnique de Paris). 
  <br>
  I started to build some small projects on my own to learn ML and I am happy to share some of these projects on this page. 
  <br><br>
  <a href="https://valentinsix.github.io">Home</a> 
  <br><br>
  <a href="/pdf/CV_2024.pdf" target="_blank">View my Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/valentin-six/" target="_blank">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/valentinsix" target="_blank">View My GitHub Profile</a>
  <br><br>
  <br><br>
  Don't hesitate to contact me via LinkedIn or per email
  <br><br>
  <a href="mailto:six.valentin@gmail.com?subject=Hello%20there!">six.valentin@gmail.com</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-6Z9FX80M12 # your Google Analytics tracking ID here
