baseURL: "https://valentinsix.github.io"
title: Valentin Six
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: Research
      url: research/
      weight: 1
    - name: Blog
      url: blog/
      weight: 2
    - name: Curriculum
      url: curriculum/
      weight: 3
    - name: Contact
      url: contact/
      weight: 4

params:
  description: "Valentin Six - Computer Science Master's Student at Georgia Tech. Research Intern at CEA-LIST working on knowledge graphs, GraphRAG, and LLM reasoning. Academic portfolio, research publications, and blog."
  author: Valentin Six
  keywords: ["Valentin Six", "Computer Science", "Georgia Tech", "Knowledge Graphs", "GraphRAG", "LLM", "Machine Learning", "Research", "Academic", "CEA-LIST", "Télécom SudParis"]
  # googleAnalyticsID: "G-XXXXX"
  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: false
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: ["research", "blog", "curriculum", "contact"]
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  schema:
    publisherType: "Person"
  assets:
    disableScrollBarStyle: true
    theme_color: "#2563eb"
    msapplication_TileColor: "#2563eb"
  profileMode:
    enabled: true
    title: Valentin Six
    subtitle:
      "I am a last-year Master's student in **Computer Science** at **[Georgia Tech](https://www.gatech.edu/)**. <br><br>
      Prior to that, I was a student at **[Télécom SudParis](https://www.telecom-sudparis.eu/en/)**, which is part of the **[Institut Polytechnique de Paris](https://www.ip-paris.fr/en)**. During those years, I mostly studied **Engineering** and **Computer Science**.<br><br>
      I am also a Research Intern at **[CEA-LIST](https://list.cea.fr/en/)**, which is related to **[Université Paris-Saclay](https://www.universite-paris-saclay.fr/en)**. <br>
      Curently, I work on knowledge injection techniques, knowledge graphs and GraphRAG for LLM reasoning."
    # imageUrl: "picture.jpeg"
    # imageWidth: 160
    # imageHeight: 160
    buttons:
      - name: Research
        url: research/
      - name: Blog
        url: blog/
      - name: Curriculum
        url: curriculum/
      - name: Contact
        url: contact/

  socialIcons:
    - name: LinkedIn
      url: https://www.linkedin.com/in/valentin-six/
    - name: GitHub
      url: https://github.com/valentinsix
    - name: CV
      url: cv.pdf
    - name: Email
      url: mailto:vsix3@gatech.edu

  assets:
    disableScrollBarStyle: true
  cover:
    hiddenInList: false
    hiddenInSingle: true
  label:
    text: "Valentin Six"
    icon: knowledge-graph.png
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
